In [323]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2

%time for _ in range(10): my_list2 = [x *2 for x in my_list]

CPU times: total: 15.6 ms
Wall time: 14 ms
CPU times: total: 750 ms
Wall time: 763 ms


### 4.1 NumPy的ndarray：一种多维数组对象

In [324]:
import numpy as np

data = np.random.randn(2, 3)

data

array([[ 0.2590664 ,  1.67116536,  1.2474178 ],
       [-1.79337242,  0.38628141,  1.09537214]])

In [325]:
data * 10

array([[  2.59066402,  16.71165363,  12.47417804],
       [-17.93372424,   3.86281412,  10.95372136]])

In [326]:
data + data

array([[ 0.5181328 ,  3.34233073,  2.49483561],
       [-3.58674485,  0.77256282,  2.19074427]])

In [327]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


#### 创建ndarray

In [328]:
data1 = [6., 7.5, 8., 0., 1.]

arr1 = np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [329]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [330]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [331]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [332]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [333]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [334]:
np.empty((2, 3, 2))

array([[[5., 5.],
        [5., 5.],
        [3., 3.]],

       [[3., 3.],
        [1., 1.],
        [1., 1.]]])

In [335]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### ndarray的数据类型

In [336]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [337]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int32


In [338]:
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

float64


In [339]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [340]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings.astype(float))

[ 1.25 -9.6  42.  ]


In [341]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(int_array.astype(calibers.dtype))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [342]:
empty_uint32 = np.empty(8, dtype='u4')

In [343]:
empty_uint32

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=uint32)

#### NumPy数组的运算

In [344]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
print(arr - arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [345]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [346]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [347]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [348]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

#### 基本的索引和切片

In [349]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [350]:
arr[5:8]

array([5, 6, 7])

In [351]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [352]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [353]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [354]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [355]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [356]:
arr2d[0][2]

3

In [357]:
arr2d[0, 2]

3

In [358]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [359]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [360]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [361]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [362]:
arr3d[1, 0]

array([7, 8, 9])

In [363]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [364]:
x[0]

array([7, 8, 9])

#### 切片索引

In [365]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [366]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [367]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [368]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [369]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [370]:
arr2d[1, :2]

array([4, 5])

In [371]:
arr2d[:2, 2]

array([3, 6])

In [372]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [373]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

#### 布尔型索引

In [374]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [375]:
data

array([[ 0.99673217,  1.98267468, -0.07222252,  1.6568538 ],
       [ 1.14125962,  0.83615093,  1.19145108, -0.07311915],
       [ 1.7056457 ,  1.16721497, -0.41578457,  0.91770284],
       [ 0.41293591,  0.05020119,  1.6735984 ,  1.02557183],
       [ 0.02315224,  1.2694505 ,  0.21428548,  0.70925718],
       [ 0.4935349 , -0.65034225,  0.3958836 , -0.60414303],
       [-2.11271977, -0.2651645 ,  0.14931583, -1.32990003]])

In [376]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [377]:
data[names == 'Bob']

array([[ 0.99673217,  1.98267468, -0.07222252,  1.6568538 ],
       [ 0.41293591,  0.05020119,  1.6735984 ,  1.02557183]])

In [378]:
data[names == 'Bob', 2:]

array([[-0.07222252,  1.6568538 ],
       [ 1.6735984 ,  1.02557183]])

In [379]:
data[names == 'Bob', 3]

array([1.6568538 , 1.02557183])

In [380]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [381]:
data[~(names == 'Bob')]

array([[ 1.14125962,  0.83615093,  1.19145108, -0.07311915],
       [ 1.7056457 ,  1.16721497, -0.41578457,  0.91770284],
       [ 0.02315224,  1.2694505 ,  0.21428548,  0.70925718],
       [ 0.4935349 , -0.65034225,  0.3958836 , -0.60414303],
       [-2.11271977, -0.2651645 ,  0.14931583, -1.32990003]])

In [382]:
cond = names == 'Bob'
data[~cond]

array([[ 1.14125962,  0.83615093,  1.19145108, -0.07311915],
       [ 1.7056457 ,  1.16721497, -0.41578457,  0.91770284],
       [ 0.02315224,  1.2694505 ,  0.21428548,  0.70925718],
       [ 0.4935349 , -0.65034225,  0.3958836 , -0.60414303],
       [-2.11271977, -0.2651645 ,  0.14931583, -1.32990003]])

In [383]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [384]:
data[mask]

array([[ 0.99673217,  1.98267468, -0.07222252,  1.6568538 ],
       [ 1.7056457 ,  1.16721497, -0.41578457,  0.91770284],
       [ 0.41293591,  0.05020119,  1.6735984 ,  1.02557183],
       [ 0.02315224,  1.2694505 ,  0.21428548,  0.70925718]])

In [385]:
data[data < 0] = 0
data

array([[0.99673217, 1.98267468, 0.        , 1.6568538 ],
       [1.14125962, 0.83615093, 1.19145108, 0.        ],
       [1.7056457 , 1.16721497, 0.        , 0.91770284],
       [0.41293591, 0.05020119, 1.6735984 , 1.02557183],
       [0.02315224, 1.2694505 , 0.21428548, 0.70925718],
       [0.4935349 , 0.        , 0.3958836 , 0.        ],
       [0.        , 0.        , 0.14931583, 0.        ]])

In [386]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.14125962, 0.83615093, 1.19145108, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.4935349 , 0.        , 0.3958836 , 0.        ],
       [0.        , 0.        , 0.14931583, 0.        ]])

#### 花式索引

In [387]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [388]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [389]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [390]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [391]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [392]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### 数组转置和轴对称

In [393]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [394]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [395]:
arr = np.random.randn(6, 3)
arr

array([[ 0.54232163, -1.21942117, -0.35567172],
       [-0.09606644,  1.48647515, -0.46682494],
       [ 0.89324931,  0.65403237, -0.25333235],
       [ 1.0883166 , -0.84738486,  0.52932492],
       [ 0.43872373, -0.86932845,  0.11375353],
       [ 0.2739467 , -0.7018183 ,  0.05987951]])

In [396]:
np.dot(arr.T, arr)

array([[ 2.55319418, -1.71578373,  0.26805205],
       [-1.71578373,  6.09069669, -1.01535324],
       [ 0.26805205, -1.01535324,  0.70531547]])

In [397]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [398]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [399]:
arr.swapaxes(1, 2)



array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])