In [159]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2

%time for _ in range(10): my_list2 = [x *2 for x in my_list]

CPU times: total: 15.6 ms
Wall time: 11.8 ms
CPU times: total: 562 ms
Wall time: 565 ms


### 4.1 NumPy的ndarray：一种多维数组对象

In [160]:
import numpy as np

data = np.random.randn(2, 3)

data

array([[ 0.8860346 ,  0.75603189, -0.67870716],
       [-0.7372262 , -0.36212329, -0.05558261]])

In [161]:
data * 10

array([[ 8.86034599,  7.56031891, -6.78707163],
       [-7.37226205, -3.62123293, -0.55582614]])

In [162]:
data + data

array([[ 1.7720692 ,  1.51206378, -1.35741433],
       [-1.47445241, -0.72424659, -0.11116523]])

In [163]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


#### 创建ndarray

In [164]:
data1 = [6., 7.5, 8., 0., 1.]

arr1 = np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [165]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [166]:
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [167]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [168]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [169]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [170]:
np.empty((2, 3, 2))

array([[[5., 5.],
        [5., 5.],
        [3., 3.]],

       [[3., 3.],
        [1., 1.],
        [1., 1.]]])

In [171]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### ndarray的数据类型

In [172]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [173]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int32


In [174]:
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

float64


In [175]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print(arr.astype(np.int32))

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [176]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
print(numeric_strings.astype(float))

[ 1.25 -9.6  42.  ]


In [177]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(int_array.astype(calibers.dtype))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [178]:
empty_uint32 = np.empty(8, dtype='u4')

In [179]:
empty_uint32

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=uint32)

#### NumPy数组的运算

In [180]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
print(arr - arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [181]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [182]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [183]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [184]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

#### 基本的索引和切片

In [185]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
arr[5:8]

array([5, 6, 7])

In [187]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [188]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [189]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [190]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [191]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [192]:
arr2d[0][2]

3

In [193]:
arr2d[0, 2]

3

In [194]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [195]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [196]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [197]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [198]:
arr3d[1, 0]

array([7, 8, 9])

In [199]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [200]:
x[0]

array([7, 8, 9])

#### 切片索引

In [201]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [202]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [203]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [204]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [205]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [206]:
arr2d[1, :2]

array([4, 5])

In [207]:
arr2d[:2, 2]

array([3, 6])

In [208]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [209]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

#### 布尔型索引

In [210]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [211]:
data

array([[ 1.09182957,  0.56821648, -0.19111435, -1.35651519],
       [-0.47627134, -1.14911552, -0.52163698,  0.53979317],
       [-0.45430546, -1.9084243 ,  0.30041053, -0.31643279],
       [ 0.78548241, -0.70039955,  1.78937208, -1.39295211],
       [-0.169148  ,  0.48853014, -0.63910178,  0.32804339],
       [-0.10756312, -2.37784178, -1.58392657, -0.73212098],
       [-0.20053881,  1.20690621, -1.31034333,  0.43046371]])

In [212]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [213]:
data[names == 'Bob']

array([[ 1.09182957,  0.56821648, -0.19111435, -1.35651519],
       [ 0.78548241, -0.70039955,  1.78937208, -1.39295211]])

In [214]:
data[names == 'Bob', 2:]

array([[-0.19111435, -1.35651519],
       [ 1.78937208, -1.39295211]])

In [215]:
data[names == 'Bob', 3]

array([-1.35651519, -1.39295211])

In [216]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [217]:
data[~(names == 'Bob')]

array([[-0.47627134, -1.14911552, -0.52163698,  0.53979317],
       [-0.45430546, -1.9084243 ,  0.30041053, -0.31643279],
       [-0.169148  ,  0.48853014, -0.63910178,  0.32804339],
       [-0.10756312, -2.37784178, -1.58392657, -0.73212098],
       [-0.20053881,  1.20690621, -1.31034333,  0.43046371]])

In [218]:
cond = names == 'Bob'
data[~cond]

array([[-0.47627134, -1.14911552, -0.52163698,  0.53979317],
       [-0.45430546, -1.9084243 ,  0.30041053, -0.31643279],
       [-0.169148  ,  0.48853014, -0.63910178,  0.32804339],
       [-0.10756312, -2.37784178, -1.58392657, -0.73212098],
       [-0.20053881,  1.20690621, -1.31034333,  0.43046371]])

In [219]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [220]:
data[mask]

array([[ 1.09182957,  0.56821648, -0.19111435, -1.35651519],
       [-0.45430546, -1.9084243 ,  0.30041053, -0.31643279],
       [ 0.78548241, -0.70039955,  1.78937208, -1.39295211],
       [-0.169148  ,  0.48853014, -0.63910178,  0.32804339]])

In [221]:
data[data < 0] = 0
data

array([[1.09182957, 0.56821648, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.53979317],
       [0.        , 0.        , 0.30041053, 0.        ],
       [0.78548241, 0.        , 1.78937208, 0.        ],
       [0.        , 0.48853014, 0.        , 0.32804339],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.20690621, 0.        , 0.43046371]])

In [222]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.53979317],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.20690621, 0.        , 0.43046371]])

#### 花式索引

In [223]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [224]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [225]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [226]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [227]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [228]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### 数组转置和轴对称

In [229]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [230]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [231]:
arr = np.random.randn(6, 3)
arr

array([[ 1.50578167, -0.32025579, -1.00426694],
       [-0.11349092, -1.11150049,  1.678147  ],
       [ 0.68735975, -0.92872896, -0.47702788],
       [-0.11900868, -0.56195676,  0.95301619],
       [ 0.91995392, -0.49495114,  0.52983646],
       [-2.246467  ,  0.90737267, -1.93621611]])

In [232]:
np.dot(arr.T, arr)

array([[ 8.65981433, -3.42129826,  2.69310257],
       [-3.42129826,  3.58463179, -3.65527593],
       [ 2.69310257, -3.65527593,  8.99018437]])

In [233]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [234]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [235]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])